//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodeksArmScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerEntities : DbContext
    {
        public SchedulerEntities()
            : base("name=SchedulerEntities")
        {
        }

        public SchedulerEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DbVersion> DbVersions { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventEmail> EventEmails { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
    }
}
